//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class computer
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string name { get; set; }
        public int processor_id { get; set; }
        public int motherboard_id { get; set; }
        public int body_id { get; set; }
        public int ram_id { get; set; }
        public int videocard_id { get; set; }
        public int ssd_id { get; set; }
        public int cooling_id { get; set; }
        public int power_unit_id { get; set; }
        public int hard_drive_id { get; set; }
        public int add_ssd_id { get; set; }
        public Nullable<int> price { get; set; }
        public string description { get; set; }
    
        public virtual add_ssd add_ssd { get; set; }
        public virtual body body { get; set; }
        public virtual cooling cooling { get; set; }
        public virtual hard_drive hard_drive { get; set; }
        public virtual motherboard motherboard { get; set; }
        public virtual power_unit power_unit { get; set; }
        public virtual processor processor { get; set; }
        public virtual ram ram { get; set; }
        public virtual ssd ssd { get; set; }
        public virtual user user { get; set; }
        public virtual videocard videocard { get; set; }
    }
}
