//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfiguratorPC.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class power_unit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public power_unit()
        {
            this.computer = new HashSet<computer>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int power { get; set; }
        public int certification_id { get; set; }
        public int cool_system_id { get; set; }
        public int price { get; set; }
        public string description { get; set; }
        public Nullable<double> rating { get; set; }
    
        public virtual certification certification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<computer> computer { get; set; }
        public virtual cool_system cool_system { get; set; }
    }
}
